name: build

on:
  push:
    paths-ignore:
      - 'LICENSE'
      - '*.md'
    branches:
      - main
  pull_request:
    paths-ignore:
      - 'LICENSE'
      - '*.md'

jobs:
  cross-platform-actions:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
        version:
          - 1.4.0
          - stable
          - devel
        exclude:
          - os: macOS-latest
            version: 1.4.0
          - os: macOS-latest
            version: devel
    steps:
      - uses: actions/checkout@v3
      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: '1.6.12'
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Print Nim version
        run: nim -v
      - name: Print Nimble version
        run: nimble -v
      - name: Install dependencies
        run: yes | nimble install
      - name: Run tests
        run: nimble test
      - name: Run build
        run: nimble build

  ubuntu-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: '1.6.12'
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Print Nim version
        run: nim -v
      - name: Print Nimble version
        run: nimble -v
      - name: Install dependencies
        run: yes | nimble install
      - name: Run tests
        run: nimble test
      - name: Run build
        run: nimble build
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: nimppt
          asset_name: NimpptRelease
          tag: ${{ github.ref }}
          overwrite: true
          body: "Nimppt release. These are CI generated."
